### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by zishiguo** [szmcdull/glinq#1]
```golang
package main

import (
	"fmt"
	. "github.com/szmcdull/glinq/unsafe"
)

func main() {
	q := []int{0, 1}
	s := FromSlice(q)
	fmt.Println(ToSlice(Skip(s, 0)))
}
```
result as follows
```golang
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/zhengjb/go #gosetup
/usr/local/go/bin/go build -o /Users/zhengjb/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_awesomeProject awesomeProject #gosetup
/Users/zhengjb/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_awesomeProject
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/szmcdull/glinq/unsafe.(*SliceEnumerator[...]).Current(0x1400012e000?)
        /Users/zhengjb/go/pkg/mod/github.com/szmcdull/glinq@v0.0.0-20231123143927-7cedaa8cac7a/unsafe/adapters.go:87 +0x44
github.com/szmcdull/glinq/unsafe.(*SkipIterator[...]).MoveNext(0x1400012c000)
        /Users/zhengjb/go/pkg/mod/github.com/szmcdull/glinq@v0.0.0-20231123143927-7cedaa8cac7a/unsafe/skip.go:47 +0x148
github.com/szmcdull/glinq/unsafe.ToSlice[...]({0x1045fa450?, 0x1400012c000?})
        /Users/zhengjb/go/pkg/mod/github.com/szmcdull/glinq@v0.0.0-20231123143927-7cedaa8cac7a/unsafe/glinq.go:37 +0x44
main.main()
        /Users/zhengjb/GolandProjects/awesomeProject/main.go:11 +0x74

Process finished with the exit code 2
```

**Comment by szmcdull** [comment]
Fixed. Please go get @latest

**Comment by zishiguo** [comment]
It works，but this case  is wrong
```golang
package main

import (
	"fmt"
	. "github.com/szmcdull/glinq/unsafe"
)

func main() {
	q1 := []int{1}
	s1 := Take(FromSlice(q1), 3)
	fmt.Println(ToSlice(s1))
	var q2 []int
	s2 := Take(FromSlice(q2), 3)
	fmt.Println(ToSlice(s2))
}
```
outputs 
```golang
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/zhengjb/go #gosetup
/usr/local/go/bin/go build -o /Users/zhengjb/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_awesomeProject awesomeProject #gosetup
/Users/zhengjb/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_awesomeProject
[1]
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/szmcdull/glinq/unsafe.(*SliceEnumerator[...]).Current(0x0?)
        /Users/zhengjb/go/pkg/mod/github.com/szmcdull/glinq@v0.0.0-20240117145937-beaceb5b7bb3/unsafe/adapters.go:82 +0x44
github.com/szmcdull/glinq/unsafe.(*TakeIterator[...]).MoveNext(0x140001000a0?)
        /Users/zhengjb/go/pkg/mod/github.com/szmcdull/glinq@v0.0.0-20240117145937-beaceb5b7bb3/unsafe/take.go:47 +0xcc
github.com/szmcdull/glinq/unsafe.ToSlice[...]({0x100bf6250?, 0x140001000a0?})
        /Users/zhengjb/go/pkg/mod/github.com/szmcdull/glinq@v0.0.0-20240117145937-beaceb5b7bb3/unsafe/glinq.go:37 +0x44
main.main()
        /Users/zhengjb/GolandProjects/awesomeProject/main.go:14 +0xf0

Process finished with the exit code 2
```

**Comment by szmcdull** [comment]
@zishiguo fixed this too. Please go get @latest

**Comment by zishiguo** [comment]
It has another question.
```golang
package main

import (
	"fmt"
	. "github.com/szmcdull/glinq/unsafe"
)

func main() {
	m1 := []int{}
	n1 := Take(Skip(FromSlice(m1), 0), 10)
	fmt.Println(ToSlice(n1))
}
```

**Comment by zishiguo** [comment]
this case is also wrong.
```golang
package main

import (
	"fmt"
	. "github.com/szmcdull/glinq/unsafe"
)

func main() {
	m1 := []int{}
	m2 := Skip(FromSlice(m1), 0)
	fmt.Println(ToSlice(m2))
}
```

**Comment by szmcdull** [comment]
@zishiguo fixed. please update

**Comment by zishiguo** [comment]
@szmcdull Thanks, it works.
